### DISCUSSION TITLE
Custom Theme Not Being Applied

### DISCUSSION THREAD

**Discussion by maweitzman** [atomiks/tippyjs#1030] [Q&A]
Recently (as of two weeks ago) my Tippy tooltips have stopped using the custom themes I've created. After looking at documentation very closely and scouring the web, I'm following all directions to a T.

Here is my JavaScript:
```js
import tippy, {roundArrow, delegate} from 'tippy.js';
import 'tippy.js/dist/svg-arrow.css';
import 'tippy.js/animations/shift-away.css';

tippy.setDefaultProps({
    allowHTML: true,
    animation: 'shift-away',
    duration: [300, 0],
    inertia: true,
    interactive: true,
    placement: 'top',
    touch: 'hold',
});

delegate('body', {
    target: '[data-tippy-content]',
});

tippy('[data-tippy-content]:not([data-tippy-unwrapped], [data-tippy-sharethis])', {
    theme: 'tailwind',
    arrow: roundArrow
});

tippy('[data-tippy-unwrapped]', {
    theme: 'unwrapped',
    placement: 'top-start'
});

tippy('[data-tippy-sharethis]', {
    theme: 'unwrapped',
    placement: 'top-start',
    onMount: (instance) => {
        window.__sharethis__.initialize();
    }
});
```

Here is my CSS where I define all the custom themes:
```css
.tippy-box[data-theme~='tailwind'] {
    @apply px-2 py-1 text-sm text-white rounded-md bg-gray-darkest;
}

.tippy-box[data-theme~='unwrapped'] {
    @apply p-0;
}

.tippy-box[data-theme~='tailwind'] > .tippy-svg-arrow {
    @apply fill-current text-gray-darkest;
}

.tippy-box[data-theme~='tailwind'][data-placement^='top'] > .tippy-arrow::before,
.tippy-box[data-theme~='tailwind'][data-placement^='right'] > .tippy-arrow::before,
.tippy-box[data-theme~='tailwind'][data-placement^='bottom'] > .tippy-arrow::before,
.tippy-box[data-theme~='tailwind'][data-placement^='left'] > .tippy-arrow::before {
    @apply border-gray-darkest;
}

.sharethis-inline-share-buttons {
    @apply space-y-2;
}

[id^="st-"] .st-btn {
    width: 100%;
    display: block !important;
}

[id^="st-"].st-has-labels .st-btn.st-remove-label > span {
    display: inline-block !important;
}
```

Can anyone help me, please?
