### ISSUE TITLE
remove border 

### ISSUE THREAD

**Issue by messizqin** [atomiks/tippyjs#1055]
hi there, I am using an element as tooltip content, but there is always a dark grey border around it, I tried to define a theme to remove it, but whatever I have tried did not work.

```css
.tippy-box {
  border: none;
  padding: 0;
}
```
