### ISSUE TITLE
Unable to change tooltip style in Webflow

### ISSUE THREAD

**Issue by yinjwang** [atomiks/tippyjs#1180]
Hi,

I'm looking to edit the background color, text color, text size, padding, and rounded corner of the tippy tooltip. I referenced `.tippy-tooltip` per answers from [this](https://github.com/atomiks/tippyjs/issues/311) ticket, but was unable to see the change in webflow)

<img width="1593" alt="Screenshot 2024-08-23 at 8 29 23 PM" src="https://github.com/user-attachments/assets/fe311eeb-2a1c-4778-9071-33d9bd065547">

For the specifics, see my post in [Webflow forum](https://discourse.webflow.com/t/adding-css-override-to-tippy-js-tooltip/290647)

Appreciate your help!

**Comment by bullet-ant** [comment]
Inspecting the tooltip, I found that it's `.tooltip-box` instead.

```css
.tooltip-box {
    font-size: 1rem;
    padding: 0.3rem 0.6rem;
    */ other css goes here /*
}
```
