### ISSUE TITLE
Changable Font Size 

### ISSUE THREAD

**Issue by gknt93** [atomiks/tippyjs#311]
Hi, tippy is absolutely amazing but when I make body font size 62.5%, tooltip becomes really small. I have to use it as an HTML so I can change.

**Comment by atomiks** [comment]
Hi,

You can override the default CSS.

(Defaults):
```css
.tippy-tooltip {
  font-size: 0.9rem;
  padding: 0.3rem 0.6rem;
}
```

Change these to a more suitable value somewhere in your CSS.
