### ISSUE TITLE
Wrap the word if it's too long

### ISSUE THREAD

**Issue by dariadomagala** [atomiks/tippyjs#319]
Hello.

I wanted to use tippy to display names that are too long to display on our site, unfortunately tippy also has a maximum width, and displays only part of a word. 
Would it be possible either to break the word if it's too long for the tooltip or configure the width of the tooltip?

**Comment by atomiks** [comment]
```css
.tippy-tooltip {
  overflow-wrap: break-word;
}
```
