### ISSUE TITLE
arrow border

### ISSUE THREAD

**Issue by jasonGonzales33** [atomiks/tippyjs#323]
I am trying to create the following:

![image](https://user-images.githubusercontent.com/32332089/46984903-5332e780-d11a-11e8-997d-1f3a4153bfde.png)

As you can see, the arrow has borders. Is this possible with tippy.js?
If so, how can I achieve this result?

**Comment by atomiks** [comment]
I'm going to add a new light bordered theme in `themes` soon.

![img](https://i.gyazo.com/997818c449302a29bfd02dcb9e90455d.png)

Here's how you make it:

```scss
.tippy-tooltip.light-border-theme {
  background: white;
  border: 1px solid rgba(0, 8, 16, 0.15);
  color: #333;
  box-shadow: 0 3px 14px -0.5px rgba(0, 8, 16, 0.1);

  .tippy-arrow {
    transform-style: preserve-3d;

    &::after {
      content: '';
      position: absolute;
      left: -8px;
      transform: translateZ(-1px);
      border-left: 8px solid transparent;
      border-right: 8px solid transparent;
    }
  }
}

/* A mixin is used for the arrow, but here it is with regular scss */

.tippy-popper[x-placement^='top']
  .tippy-tooltip.light-border-theme
  .tippy-arrow {
  border-top-color: #fff;

  &::after {
    top: -7px;
    border-top: 8px solid rgba(0, 8, 16, 0.15);
  }
}

.tippy-popper[x-placement^='bottom']
  .tippy-tooltip.light-border-theme
  .tippy-arrow {
  border-bottom-color: #fff;

  &::after {
    bottom: -7px;
    border-bottom: 8px solid rgba(0, 8, 16, 0.15);
  }
}

/* And left/right if necessary */
```
