### ISSUE TITLE
Is maxWidth still valid?

### ISSUE THREAD

**Issue by darrensw777** [atomiks/tippyjs#361]
I need to set a width on the tooltips, failing that a maximum width.

When trying to use `maxWidth` I get the following error:

`Error: [tippy]: maxWidth is not a valid option`

Has it been removed? If so, is there an alternative? You can't style reliably with simple css as it then throws positioning out.

**Comment by atomiks** [comment]
It was removed. You can still add a max width via a theme if need be.

But I'm pretty sure it can be added back in if this media query is removed and its properties added to the base-level selector. That will keep the appropriate padding for mobile if the maxWidth is more than 350px, so it doesn't overflow.

It was there from literally the first version and I didn't really touch it since, the fallback 96% isn't necessary with calc() support now 

```css
@media (max-width: 360px) {
  .tippy-popper {
    max-width: 96%;
    max-width: calc(100% - 20px);
  }
}
```
