### ISSUE TITLE
When using HTML content, text gets centered

### ISSUE THREAD

**Issue by heruan** [atomiks/tippyjs#507]
When using HTML content, text gets centered. When the content is HTML, it would be preferable not to override its style.

CodePen: https://codepen.io/anon/pen/LoBgJG

**Comment by atomiks** [comment]
Don't think it's easy to differentiate HTML content and text content here.

I would usually just use a simple theme:

```css
.tippy-tooltip.left-align-theme {
  text-align: left;
}
```

```js
tippy(ref, {
  theme: 'light left-align'
});
```
