### ISSUE TITLE
scrolling the item that opened the tippy out of view doesn't close it

### ISSUE THREAD

**Issue by mreinstein** [atomiks/tippyjs#555]
## Bug description
If the reference element scrolls out of the viewport, I'd expect the tippy to close automatically

## Reproduction
1. click on a reference element, which opens a tippy
2. scroll way down the page
3. notice the tippy is still open

![scroll](https://user-images.githubusercontent.com/718067/62737459-aeed9a80-b9e4-11e9-8fb8-da7d4f56ebe3.gif)

**Comment by mreinstein** [comment]
btw this probably gives you an idea of why I was saying this stuff will be in front of millions of eyeballs :)

**Comment by atomiks** [comment]
v4

```css
.tippy-popper[x-out-of-boundaries] {
  display: none;
}
```

v5

```css
.tippy-tooltip[data-out-of-boundaries] {
  display: none;
}
```
