### ISSUE TITLE
Tippy arrow not as pseudo element

### ISSUE THREAD

**Issue by vukvukovich** [atomiks/tippyjs#658]
## Problem

If you wish to manipulate tippy CSS live, ex. to make tippy CSS previewer or similar (choosing colors, borders and stuff). It is not possible to change Tippy arrow color/border since it has pseudo elements which cannot be manipulated through JS. 

Any thoughts?

Cheers

## Solution

It would be better if tippy arrow was an element instead of pseudo element.

**Comment by atomiks** [comment]
The arrow is a real element, the pseduo-elements are for the borders in the `light-border` theme

**Comment by vukvukovich** [comment]
Exactly. If you with to change them on the fly it is not possible to access directly. Only to load another css. Just my two cents.

**Comment by atomiks** [comment]
Maybe you could use CSS variables and override the border styles. Then in JS, it's accessible to change via `elementWithCSSVariable.style.setProperty('--property', 'value');`

```css
body {
  --tippy-background-color: #fff;
  --tippy-border-color: rgba(0, 8, 16, 0.2);
}

/* Style each placement */
.tippy-tooltip.dynamic-theme[data-placement^='top'] > .tippy-arrow {
  border-top-color: var(--tippy-background-color);
}
.tippy-tooltip.dynamic-theme[data-placement^='top'] > .tippy-arrow:after {
  border-top-color: var(--tippy-background-color);
}
.tippy-tooltip.dynamic-theme[data-placement^='top'] > .tippy-arrow:before {
  border-top-color: var(--tippy-border-color);
}
```

```js
document.body.style.setProperty('--tippy-background-color', 'pink');
document.body.style.setProperty('--tippy-border-color', 'white');
```
