### ISSUE TITLE
Tippy 6 migration guide : say that [data-of-boundary] was removed

### ISSUE THREAD

**Issue by matthieu60** [atomiks/tippyjs#714]
While testing tippy v6 I noticed that `[data-out-of-boundaries]` has been removed, and that it's not explained in the migration guide.

From what I understand, the removal is voluntary because the main use case (scrolling) is now handled automatically, but there were other use cases for this attributes, for instance to prevent showing a tooltip linked to an element that is currently hidden.

In my use case I had to do that:

```css
/* v5 */
.tippy-tooltip[data-out-of-boundaries] {
  opacity: 0;
}

/* v6 */
[data-tippy-root][data-popper-reference-hidden] {
  opacity: 0;
}
```

Let me know if you'd be interested in more info on the use case or a PR for the docs.
