### ISSUE TITLE
Improve arrow themes documentation

### ISSUE THREAD

**Issue by woothu** [atomiks/tippyjs#738]
## Bug description

Docs are not updated to the 6.1 version. i.e
https://atomiks.github.io/tippyjs/v6/themes/#css-arrow

**Comment by atomiks** [comment]
https://atomiks.github.io/tippyjs/v6/themes/#arrow-border?

**Comment by woothu** [comment]
In css-arrow section instead of 

```css
.tippy-box[data-theme~='tomato'][data-placement^='top'] > .tippy-arrow::before {
  border-top-color: tomato;
}
.tippy-box[data-theme~='tomato'][data-placement^='bottom'] > .tippy-arrow::before {
  border-bottom-color: tomato;
}
.tippy-box[data-theme~='tomato'][data-placement^='left'] > .tippy-arrow::before {
  border-left-color: tomato;
}
.tippy-box[data-theme~='tomato'][data-placement^='right'] > .tippy-arrow::before {
  border-right-color: tomato;
}
```

Users can:
```css
.tippy-box[data-theme~='tomato'] > .tippy-arrow::before {
  border-color: tomato;
}
```

If so, the description of the section is also obsolete
